import type {
  Citation,
  EvidenceLink,
  EvidenceQuality,
  Finding,
  IdeaCandidate,
  ResearchQuestion,
  Source,
} from './types';

export interface DemoFixture {
  source: Source;
  findings: Finding[];
}

const retrievedAt = '2026-08-29T00:00:00.000Z';

const quality = (overrides: Partial<EvidenceQuality> = {}): EvidenceQuality => ({
  directness: 'moderate',
  relevance: 'moderate',
  recency: 'moderate',
  methodTransparency: 'moderate',
  independence: 'strong',
  specificity: 'moderate',
  contextCompleteness: 'moderate',
  ...overrides,
});

function citation(source: Source, exactExcerpt: string, pageOrSection: string): Citation {
  return {
    sourceId: source.id,
    sourceTitle: source.title,
    authorOrPublisher: source.author || source.publisher,
    publishedDate: source.publishedAt,
    urlOrDocumentId: source.url,
    pageOrSection,
    exactExcerpt,
    retrievedAt,
    accessMode: source.accessMode,
  };
}

const sources = {
  analytics: {
    id: 'source-analytics',
    lane: 'first_party',
    sourceType: 'analytics',
    title: 'Demo GA4 setup-funnel export',
    author: 'LaunchPad demo dataset',
    publisher: 'Synthetic first-party data',
    publishedAt: '2026-08-28',
    url: 'document://demo-ga4-setup-funnel.csv',
    accessMode: 'private',
    userProvided: true,
    synthetic: true,
    private: true,
    contentHash: 'demo-ga4-v1',
    sourceFamilyId: 'family-demo-analytics',
    retrievalStatus: 'available',
    extractionStatus: 'pending',
  },
  support: {
    id: 'source-support',
    lane: 'customer',
    sourceType: 'customer',
    title: 'Anonymized setup-support sample',
    author: 'LaunchPad demo dataset',
    publisher: 'Synthetic first-party data',
    publishedAt: '2026-08-28',
    url: 'document://demo-support-sample.csv',
    accessMode: 'private',
    userProvided: true,
    synthetic: true,
    private: true,
    contentHash: 'demo-support-v1',
    sourceFamilyId: 'family-demo-support',
    retrievalStatus: 'available',
    extractionStatus: 'pending',
  },
  sweller: {
    id: 'source-sweller',
    lane: 'academic',
    sourceType: 'paper',
    title: 'Cognitive load during problem solving: Effects on learning',
    author: 'John Sweller',
    publisher: 'Cognitive Science',
    publishedAt: '1988-04-01',
    url: 'https://doi.org/10.1016/0364-0213(88)90023-7',
    accessMode: 'public',
    userProvided: false,
    synthetic: false,
    private: false,
    contentHash: 'doi-10-1016-0364-0213-88-90023-7',
    sourceFamilyId: 'family-sweller-1988',
    retrievalStatus: 'metadata_only',
    extractionStatus: 'pending',
  },
  schwanke: {
    id: 'source-schwonke',
    lane: 'academic',
    sourceType: 'paper',
    title: 'Effects of different ratios of worked solution steps and problem solving opportunities',
    author: 'Rolf Schwonke et al.',
    publisher: 'Computers in Human Behavior',
    publishedAt: '2011-01-01',
    url: 'https://doi.org/10.1016/j.chb.2010.03.037',
    accessMode: 'public',
    userProvided: false,
    synthetic: false,
    private: false,
    contentHash: 'doi-10-1016-j-chb-2010-03-037',
    sourceFamilyId: 'family-schwonke-2011',
    retrievalStatus: 'metadata_only',
    extractionStatus: 'pending',
  },
  govuk: {
    id: 'source-govuk',
    lane: 'market',
    sourceType: 'report',
    title: 'Learning about users and their needs',
    author: 'User research community',
    publisher: 'GOV.UK Service Manual',
    publishedAt: '2017-03-23',
    url: 'https://www.gov.uk/service-manual/user-research/start-by-learning-user-needs',
    accessMode: 'public',
    userProvided: false,
    synthetic: false,
    private: false,
    contentHash: 'govuk-user-needs-2017',
    sourceFamilyId: 'family-govuk-user-needs',
    retrievalStatus: 'available',
    extractionStatus: 'pending',
  },
  w3c: {
    id: 'source-w3c',
    lane: 'market',
    sourceType: 'report',
    title: 'Cognitive Accessibility Objective: Provide Help and Support',
    author: 'Cognitive and Learning Disabilities Accessibility Task Force',
    publisher: 'W3C Web Accessibility Initiative',
    publishedAt: '2021-04-29',
    url: 'https://www.w3.org/WAI/WCAG2/supplemental/objectives/o7-support/',
    accessMode: 'public',
    userProvided: false,
    synthetic: false,
    private: false,
    contentHash: 'w3c-coga-support-o7',
    sourceFamilyId: 'family-w3c-coga',
    retrievalStatus: 'available',
    extractionStatus: 'pending',
  },
  communityOne: {
    id: 'source-community-1',
    lane: 'community',
    sourceType: 'community',
    title: 'User-provided community observation A',
    author: 'Synthetic demo participant',
    publisher: 'User-provided excerpt',
    publishedAt: '2026-08-28',
    url: 'document://community-observation-a.txt',
    accessMode: 'user_provided',
    userProvided: true,
    synthetic: true,
    private: false,
    contentHash: 'community-demo-a',
    sourceFamilyId: 'family-community-demo-a',
    retrievalStatus: 'available',
    extractionStatus: 'pending',
  },
  communityTwo: {
    id: 'source-community-2',
    lane: 'community',
    sourceType: 'community',
    title: 'User-provided community observation B',
    author: 'Synthetic demo participant',
    publisher: 'User-provided excerpt',
    publishedAt: '2026-08-28',
    url: 'document://community-observation-b.txt',
    accessMode: 'user_provided',
    userProvided: true,
    synthetic: true,
    private: false,
    contentHash: 'community-demo-b',
    sourceFamilyId: 'family-community-demo-b',
    retrievalStatus: 'available',
    extractionStatus: 'pending',
  },
  tutorialControl: {
    id: 'source-tutorial-control',
    lane: 'counter',
    sourceType: 'report',
    title: 'Flash Usability Report',
    author: 'Nielsen Norman Group',
    publisher: 'Nielsen Norman Group',
    publishedAt: '2009-01-01',
    url: 'https://media.nngroup.com/media/reports/free/Website_Tools_and_Applications_with_Flash.pdf',
    accessMode: 'public',
    userProvided: false,
    synthetic: false,
    private: false,
    contentHash: 'nng-flash-usability-report',
    sourceFamilyId: 'family-nng-tutorial-control',
    retrievalStatus: 'available',
    extractionStatus: 'pending',
  },
} satisfies Record<string, Source>;

export const DEMO_FIXTURES: DemoFixture[] = [
  {
    source: sources.analytics,
    findings: [{
      id: 'finding-analytics',
      sourceId: sources.analytics.id,
      normalizedClaim: '43% of new-administrator sessions ended at the integration step before a first valuable action.',
      evidenceType: 'first_party_behavioral',
      value: 43,
      unit: 'percent',
      denominator: '420 sessions',
      population: '420 new-administrator sessions',
      sampleSize: 420,
      geography: 'Demo company, global accounts',
      timeframe: 'Last 90 days',
      direct: true,
      caveats: ['Synthetic GA4 export created for the hackathon demo.', 'Observed abandonment does not establish cause.'],
      reviewStatus: 'pending',
      extractionConfidence: 'strong',
      quality: quality({ directness: 'strong', relevance: 'strong', methodTransparency: 'strong', specificity: 'strong', contextCompleteness: 'strong', independence: 'moderate' }),
      citation: citation(sources.analytics, '181 of 420 new-administrator sessions ended at setup_step=integration before first_value_event.', 'Rows 2–421; derived funnel summary'),
      synthetic: true,
    }],
  },
  {
    source: sources.support,
    findings: [{
      id: 'finding-support',
      sourceId: sources.support.id,
      normalizedClaim: '31 of 50 sampled setup tickets asked how to locate or validate integration credentials.',
      evidenceType: 'primary_user_evidence',
      value: 31,
      unit: 'tickets',
      denominator: '50 sampled setup tickets',
      population: '50 anonymized setup-support tickets',
      sampleSize: 50,
      geography: 'Demo company, mid-market accounts',
      timeframe: 'Last 90 days',
      direct: true,
      caveats: ['Synthetic and anonymized sample.', 'Support-ticket users may not represent silent abandoners.'],
      reviewStatus: 'pending',
      extractionConfidence: 'strong',
      quality: quality({ directness: 'strong', relevance: 'strong', methodTransparency: 'strong', specificity: 'strong', contextCompleteness: 'strong', independence: 'moderate' }),
      citation: citation(sources.support, '31 of 50 tickets contain credential-location or credential-validation questions during setup.', 'Coded summary; codes CRED-LOC and CRED-VAL'),
      synthetic: true,
    }],
  },
  {
    source: sources.sweller,
    findings: [{
      id: 'finding-cognitive-load',
      sourceId: sources.sweller.id,
      normalizedClaim: 'Unstructured means-ends problem solving can consume cognitive capacity that would otherwise support learning.',
      evidenceType: 'primary_research',
      population: 'Problem-solving learners studied in the cited experiments',
      geography: 'Research context',
      timeframe: 'Published 1988',
      direct: true,
      caveats: ['Learning research is analogous mechanism evidence, not a direct SaaS onboarding trial.'],
      reviewStatus: 'pending',
      extractionConfidence: 'strong',
      quality: quality({ directness: 'moderate', methodTransparency: 'strong', independence: 'strong', contextCompleteness: 'strong' }),
      citation: citation(sources.sweller, 'Conventional problem solving in the form of means-ends analysis requires a relatively large amount of cognitive processing capacity.', 'Abstract'),
      synthetic: false,
    }],
  },
  {
    source: sources.schwanke,
    findings: [{
      id: 'finding-worked-examples',
      sourceId: sources.schwanke.id,
      normalizedClaim: 'Worked examples reduced extraneous load relative to unguided problem solving in the reported experiment.',
      evidenceType: 'primary_research',
      population: '125 high-school students in a geometry lesson',
      sampleSize: 125,
      geography: 'Research context',
      timeframe: 'Published 2011',
      direct: true,
      caveats: ['Education setting differs from administrator onboarding.', 'The paper reports mixed effects across outcome and difficulty.'],
      reviewStatus: 'pending',
      extractionConfidence: 'strong',
      quality: quality({ methodTransparency: 'strong', independence: 'strong', contextCompleteness: 'strong' }),
      citation: citation(sources.schwanke, 'Problem solving induced more extraneous load than studying worked examples.', 'Abstract'),
      synthetic: false,
    }],
  },
  {
    source: sources.govuk,
    findings: [{
      id: 'finding-assumption-discipline',
      sourceId: sources.govuk.id,
      normalizedClaim: 'Ideas not grounded in user evidence should remain visible as assumptions to test.',
      evidenceType: 'secondary_research',
      population: 'Teams designing public services',
      geography: 'United Kingdom',
      timeframe: 'Guidance updated 2017',
      direct: true,
      caveats: ['Service-design guidance, not a controlled experiment.'],
      reviewStatus: 'pending',
      extractionConfidence: 'strong',
      quality: quality({ directness: 'strong', methodTransparency: 'moderate', independence: 'strong', contextCompleteness: 'strong' }),
      citation: citation(sources.govuk, 'Treat any opinions or suggestions that do not come from users as assumptions that have to be proven by doing research.', 'Researching users and their needs'),
      synthetic: false,
    }],
  },
  {
    source: sources.w3c,
    findings: [{
      id: 'finding-contextual-help',
      sourceId: sources.w3c.id,
      normalizedClaim: 'Interfaces should explain choices and provide help close to task difficulty.',
      evidenceType: 'expert_opinion',
      population: 'People with cognitive and learning disabilities and the broader public',
      geography: 'Web guidance',
      timeframe: 'Published 2021',
      direct: true,
      caveats: ['Accessibility guidance establishes a design objective, not an activation uplift estimate.'],
      reviewStatus: 'pending',
      extractionConfidence: 'strong',
      quality: quality({ directness: 'strong', relevance: 'strong', independence: 'strong', contextCompleteness: 'strong' }),
      citation: citation(sources.w3c, 'Explain choices to help the user successfully complete their tasks.', 'Description'),
      synthetic: false,
    }],
  },
  {
    source: sources.communityOne,
    findings: [{
      id: 'finding-community-peer',
      sourceId: sources.communityOne.id,
      normalizedClaim: 'One demo participant preferred copying a peer configuration over following the product setup guide.',
      evidenceType: 'community_anecdote',
      population: 'One synthetic community participant',
      sampleSize: 1,
      geography: 'Synthetic community sample',
      timeframe: 'Demo observation',
      direct: true,
      caveats: ['Synthetic single-person anecdote.', 'Not independently retrieved.', 'Cannot establish prevalence.'],
      reviewStatus: 'pending',
      extractionConfidence: 'strong',
      quality: quality({ relevance: 'moderate', recency: 'strong', methodTransparency: 'weak', independence: 'unknown', specificity: 'strong', contextCompleteness: 'weak', directness: 'weak' }),
      citation: citation(sources.communityOne, 'I copied another admin’s configuration because the setup guide did not tell me what good looked like.', 'User-provided synthetic excerpt'),
      synthetic: true,
    }],
  },
  {
    source: sources.communityTwo,
    findings: [{
      id: 'finding-community-office-hours',
      sourceId: sources.communityTwo.id,
      normalizedClaim: 'One demo participant said live peer office hours would make setup feel safer.',
      evidenceType: 'community_anecdote',
      population: 'One synthetic community participant',
      sampleSize: 1,
      geography: 'Synthetic community sample',
      timeframe: 'Demo observation',
      direct: true,
      caveats: ['Synthetic single-person anecdote.', 'Expressed preference is not observed behavior.'],
      reviewStatus: 'pending',
      extractionConfidence: 'strong',
      quality: quality({ relevance: 'moderate', recency: 'strong', methodTransparency: 'weak', independence: 'unknown', specificity: 'moderate', contextCompleteness: 'weak', directness: 'weak' }),
      citation: citation(sources.communityTwo, 'Weekly office hours with experienced admins would make me more confident before I connect production data.', 'User-provided synthetic excerpt'),
      synthetic: true,
    }],
  },
  {
    source: sources.tutorialControl,
    findings: [{
      id: 'finding-tutorial-control',
      sourceId: sources.tutorialControl.id,
      normalizedClaim: 'Guided onboarding can backfire if users cannot control or skip it.',
      evidenceType: 'counter_evidence',
      population: 'Users of interactive web tools covered by the report',
      geography: 'Web usability research',
      timeframe: 'Published 2009',
      direct: true,
      caveats: ['Older report.', 'Flash-era interaction patterns differ from current SaaS products.'],
      reviewStatus: 'pending',
      extractionConfidence: 'strong',
      quality: quality({ recency: 'weak', methodTransparency: 'moderate', independence: 'strong', contextCompleteness: 'moderate' }),
      citation: citation(sources.tutorialControl, 'When possible, give users control over the tutorial.', 'Tutorial guidance'),
      synthetic: false,
    }],
  },
];

export const RESEARCH_QUESTION_TEMPLATES: ResearchQuestion[] = [
  { id: 'rq-first-party', lane: 'first_party', question: 'Where do new administrators abandon setup before reaching first value?', purpose: 'Locate the highest-friction behavioral step.', priority: 'high', preferredSourceTypes: ['analytics', 'CSV export'], timeframe: 'Last 90 days', query: 'new administrator setup funnel first value', status: 'planned', locked: false },
  { id: 'rq-customer', lane: 'customer', question: 'What questions or workarounds recur in setup-support evidence?', purpose: 'Find the language and needs behind observed abandonment.', priority: 'high', preferredSourceTypes: ['support tickets', 'interviews'], timeframe: 'Last 90 days', query: 'administrator setup support credential help', status: 'planned', locked: false },
  { id: 'rq-academic', lane: 'academic', question: 'Which mechanisms explain failure during complex first-run tasks?', purpose: 'Test cognitive-load and guidance mechanisms.', priority: 'high', preferredSourceTypes: ['primary research', 'review papers'], timeframe: 'Any; prefer recent replications', query: 'worked examples cognitive load novice task guidance', status: 'planned', locked: false },
  { id: 'rq-market', lane: 'market', question: 'What established service and accessibility guidance applies?', purpose: 'Find transferable design constraints.', priority: 'medium', preferredSourceTypes: ['standards', 'public guidance'], timeframe: 'Current guidance', query: 'task help user needs accessibility guidance', status: 'planned', locked: false },
  { id: 'rq-community', lane: 'community', question: 'What do administrators say they want during setup?', purpose: 'Collect weak signals without equating them to behavior.', priority: 'low', preferredSourceTypes: ['user-provided excerpts'], timeframe: 'Recent', query: 'administrator setup workaround peer help', status: 'planned', locked: false },
  { id: 'rq-counter', lane: 'counter', question: 'What evidence argues against mandatory guided onboarding?', purpose: 'Challenge the obvious solution before finalization.', priority: 'high', preferredSourceTypes: ['contradictory studies', 'usability reports'], timeframe: 'Any relevant period', query: 'tutorial control skip guidance expertise reversal', status: 'planned', locked: false },
];

export function createCandidateFixtures(): { candidates: IdeaCandidate[]; links: EvidenceLink[] } {
  const candidates: IdeaCandidate[] = [
    {
      id: 'candidate-a',
      name: 'Admin Guild',
      oneLiner: 'A peer-led setup concierge that pairs new administrators with proven configurations and live office hours.',
      targetUser: 'New administrators who feel uncertain about production configuration',
      problem: 'Setup lacks a trusted picture of what good looks like.',
      mechanism: 'Peer reassurance and reusable examples reduce perceived setup risk.',
      workflow: ['Choose a peer pattern', 'Copy a proven configuration', 'Join an expert office hour if blocked'],
      features: [
        { id: 'peer-playbooks', name: 'Peer playbooks', description: 'Copy setup patterns attributed to experienced administrators.' },
        { id: 'office-hours', name: 'Live office hours', description: 'Escalate uncertainty to a rotating administrator community.' },
        { id: 'community-proof', name: 'Community proof', description: 'Show how similar teams configured each integration.' },
      ],
      expectedOutcome: 'Increase confidence and reduce support dependency during setup.',
      implementationConstraints: ['Six-week delivery', 'No additional support headcount'],
      differentiation: 'Turns onboarding into a peer network rather than a product tour.',
      assumptions: [{ id: 'assumption-a-1', statement: 'Community participation will be sufficient at launch.', importance: 'critical', evidenceStatus: 'unsupported', validationMethod: 'Recruit 10 experienced admins and measure response coverage.' }],
      coverage: 0,
      score: 0,
      noveltyBonus: 18,
      unsupportedComponents: [],
      status: 'candidate',
    },
    {
      id: 'candidate-b',
      name: 'First-Value Flightpath',
      oneLiner: 'An adaptive setup route that demonstrates one valuable outcome first, then reveals only the configuration needed for that route.',
      targetUser: 'New administrators with different levels of product and integration expertise',
      problem: 'Administrators configure too much before seeing a meaningful outcome.',
      mechanism: 'Worked examples and contextual help reduce avoidable cognitive load while opt-out controls preserve expert autonomy.',
      workflow: ['Choose the first outcome', 'Preview a completed example', 'Connect the minimum inputs', 'See first value', 'Continue or exit guidance'],
      features: [
        { id: 'outcome-preview', name: 'Outcome preview', description: 'Show a completed first-value example before asking for configuration.' },
        { id: 'credential-coach', name: 'Credential coach', description: 'Explain credential choices in context and validate them inline.' },
        { id: 'adaptive-rails', name: 'Adaptive rails', description: 'Let experienced admins skip guidance while novices reveal worked steps.' },
      ],
      expectedOutcome: 'Improve first-session activation without adding support headcount.',
      implementationConstraints: ['Six-week delivery', 'Use existing product architecture', 'No additional support headcount'],
      differentiation: 'Optimizes for first value rather than setup completion and changes guidance by expertise.',
      assumptions: [
        { id: 'assumption-b-1', statement: 'Seeing a completed outcome increases willingness to connect data.', importance: 'critical', evidenceStatus: 'partial', validationMethod: 'Prototype test with new administrators.' },
        { id: 'assumption-b-2', statement: 'The existing architecture can render a safe preview with sample data.', importance: 'high', evidenceStatus: 'unsupported', validationMethod: 'Two-day engineering spike.' },
      ],
      coverage: 0,
      score: 0,
      noveltyBonus: 10,
      unsupportedComponents: [],
      status: 'candidate',
    },
    {
      id: 'candidate-c',
      name: 'Readiness Passport',
      oneLiner: 'A preflight that checks access, data, and ownership before setup begins and routes each blocker to the right owner.',
      targetUser: 'Administrators coordinating setup across technical and business owners',
      problem: 'Setup starts before prerequisites and decision owners are ready.',
      mechanism: 'Making prerequisites and ownership visible prevents avoidable integration dead ends.',
      workflow: ['Run readiness check', 'Assign missing prerequisites', 'Resume setup when green'],
      features: [
        { id: 'preflight', name: 'Readiness preflight', description: 'Validate permissions and required data before setup.' },
        { id: 'owner-routing', name: 'Owner routing', description: 'Send each blocker to the person who can resolve it.' },
        { id: 'resume-point', name: 'Durable resume point', description: 'Return administrators to the exact blocked step.' },
      ],
      expectedOutcome: 'Reduce failed setup attempts and repeated support contacts.',
      implementationConstraints: ['Six-week delivery', 'Requires permission introspection'],
      differentiation: 'Treats onboarding as operational readiness rather than education.',
      assumptions: [{ id: 'assumption-c-1', statement: 'Missing prerequisites explain a material share of abandonment.', importance: 'critical', evidenceStatus: 'partial', validationMethod: 'Add prerequisite codes to 30 failed sessions.' }],
      coverage: 0,
      score: 0,
      noveltyBonus: 5,
      unsupportedComponents: [],
      status: 'candidate',
    },
  ];

  const specs: Array<Omit<EvidenceLink, 'id'>> = [
    { candidateId: 'candidate-a', componentPath: 'mechanism', insightId: 'insight-friction', findingId: 'finding-analytics', relationshipType: 'supports', explanation: 'Behavioral abandonment establishes a real setup problem.' },
    { candidateId: 'candidate-a', componentPath: 'features.0', insightId: 'insight-confidence', findingId: 'finding-community-peer', relationshipType: 'supports', explanation: 'The peer-playbook feature comes directly from the copied-configuration anecdote.' },
    { candidateId: 'candidate-a', componentPath: 'features.1', insightId: 'insight-confidence', findingId: 'finding-community-office-hours', relationshipType: 'supports', explanation: 'The office-hours feature follows the expressed preference for live peer reassurance.' },
    { candidateId: 'candidate-a', componentPath: 'features.1', insightId: 'insight-friction', findingId: 'finding-support', relationshipType: 'qualifies', explanation: 'Recurring credential questions show a help need, but do not prove live help is best.' },
    { candidateId: 'candidate-a', componentPath: 'features.2', insightId: 'insight-confidence', findingId: 'finding-community-peer', relationshipType: 'supports', explanation: 'Community proof represents the peer example the participant sought.' },
    { candidateId: 'candidate-b', componentPath: 'mechanism', insightId: 'insight-guidance', findingId: 'finding-cognitive-load', relationshipType: 'supports', explanation: 'The mechanism reduces unstructured problem-solving load.' },
    { candidateId: 'candidate-b', componentPath: 'mechanism', insightId: 'insight-friction', findingId: 'finding-analytics', relationshipType: 'supports', explanation: 'The intervention targets the observed integration-step abandonment.' },
    { candidateId: 'candidate-b', componentPath: 'features.0', insightId: 'insight-guidance', findingId: 'finding-worked-examples', relationshipType: 'supports', explanation: 'A completed outcome is a worked example before independent configuration.' },
    { candidateId: 'candidate-b', componentPath: 'features.1', insightId: 'insight-friction', findingId: 'finding-support', relationshipType: 'supports', explanation: 'Credential help targets the dominant support-ticket pattern.' },
    { candidateId: 'candidate-b', componentPath: 'features.1', insightId: 'insight-guidance', findingId: 'finding-contextual-help', relationshipType: 'supports', explanation: 'Inline explanations follow the accessibility guidance to explain choices.' },
    { candidateId: 'candidate-b', componentPath: 'features.2', insightId: 'insight-contradiction', findingId: 'finding-tutorial-control', relationshipType: 'qualifies', explanation: 'Opt-out controls answer evidence that tutorials should remain user-controlled.' },
    { candidateId: 'candidate-c', componentPath: 'mechanism', insightId: 'insight-friction', findingId: 'finding-support', relationshipType: 'supports', explanation: 'Credential questions suggest readiness gaps before setup.' },
    { candidateId: 'candidate-c', componentPath: 'features.0', insightId: 'insight-friction', findingId: 'finding-analytics', relationshipType: 'supports', explanation: 'The preflight sits immediately before the observed drop-off step.' },
    { candidateId: 'candidate-c', componentPath: 'features.1', insightId: 'insight-assumptions', findingId: 'finding-assumption-discipline', relationshipType: 'qualifies', explanation: 'Ownership routing remains a hypothesis requiring user evidence.' },
  ];

  return {
    candidates,
    links: specs.map((link, index) => ({ ...link, id: `evidence-link-${index + 1}` })),
  };
}
